/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index.tsx'
import { Route as NotebookNotebookImport } from './routes/notebook.$notebook.tsx'
import { Route as NoteNoteImport } from './routes/note.$note.tsx'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NotebookNotebookRoute = NotebookNotebookImport.update({
  path: '/notebook/$notebook',
  getParentRoute: () => rootRoute,
} as any)

const NoteNoteRoute = NoteNoteImport.update({
  path: '/note/$note',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/note/$note': {
      preLoaderRoute: typeof NoteNoteImport
      parentRoute: typeof rootRoute
    }
    '/notebook/$notebook': {
      preLoaderRoute: typeof NotebookNotebookImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  NoteNoteRoute,
  NotebookNotebookRoute,
])

/* prettier-ignore-end */
